### PR TITLE
Implement harfbuzz, update fontconfig, freetype, expat, and other fixes

### LINKED ISSUE #9: update libass or add harfbuzz !!
hi,
i  used right to left language [ arabic ], and libass doesn't support all the character for all language rtl,
i tried to add harfbuzz and compile it but i get error in build,
for now i used SubtitlesOctopus in other language but for arabic [rtl] language libass doesn't .
harfbuzz is a best solution for this issue, and for all rtl languages,
if you would can make another version of SubtitlesOctopus with harfbuzz that would be highly great,
thanks

### PR DESCRIPTION
**Pull request by TFSThiagoBR98**
Fixes #9 #13, and other fixes

### CODE REVIEW

**Comment by TFSThiagoBR98** [comment]
This speed up the rendering on Chrome V8, and i fixed the dispose not remove the canvas element.

**Comment by Dador** [comment]
Thanks for contributing!
Right now I'm a bit busy but I'll check it soon.

> but is slow on Firefox
Is there big difference comparing to old version?

**Comment by TFSThiagoBR98** [comment]
Compared to old version, this version is a little faster. But i need some performance test scripts to prove it.

**Comment by TFSThiagoBR98** [comment]
Add this to create Benchmark script
```javascript
    var debounce = true;
    var seconds  = 5; // set to 15 instead

    var isFirstRun = true;
    var changeResolution = function (width, height) {
        player.width(width).height(height);
        octopusInstance.resize();
    };
    var runBenchmark = function () {
        changeResolution(1280, 720);
        octopusInstance.runBenchmark();
        console.log("Test benchmark at " + player.currentTime())
    };

    player.ready(function () {
        // This would look more nice as a plugin but is's just as showcase of using with custom players
        var video = this.tech_.el_;
        player.on('timeupdate', function(event){
            var hasPlayedTime = player.currentTime();
            var intPlayedTime = parseInt(hasPlayedTime, 10);
            var isFifteen     = intPlayedTime % seconds === 0 && intPlayedTime !== 0;
            
            if (isFifteen && debounce) {
                debounce = false;
                runBenchmark();
            } else {
                setTimeout(function() {
                    debounce = true;
                }, 1000);
            }
        });
```

The results are in the log files 
[localhost-old.log](https://github.com/Dador/JavascriptSubtitlesOctopus/files/1461963/localhost-old.log)
[localhost-new.log](https://github.com/Dador/JavascriptSubtitlesOctopus/files/1461964/localhost-new.log)

 Used: Chromium 63.0.3236.0 x64 Windows 10

**Comment by TFSThiagoBR98** [comment]
Now i'm working on update for fribidi

**Comment by TFSThiagoBR98** [comment]
After some work and patch fixes, i'm able to incrase the speed on Firefox, i will push more fixes soon

**Comment by anoosi** [comment]
that issue #9 fixed in this pull!
and work like charm...
too much thanks @TFSThiagoBR98

**Comment by Dador** [comment]
Sorry for a big delay.

I've checked and everything working correctly! (after small fix for latest version of emscripten)
I've merged it. Feel free to sent pull requests again. I'll try to be faster with them :)

Thanks! 👍

**Pull request merged**
